#!/bin/bash
# zoom-course-automation セットアップウィザード
# .env ファイルを対話形式で作成する
#
# 使い方:
#   bash setup.sh

set -e

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$PKG_DIR/scripts/.env"
ENV_EXAMPLE="$PKG_DIR/.env.example"

echo ""
echo "================================================="
echo "  zoom-course-automation セットアップウィザード"
echo "================================================="
echo ""

# 既存 .env チェック
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  既に $ENV_FILE が存在します。"
    read -p "上書きしますか?(yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        echo "中止しました。"
        exit 0
    fi
    cp "$ENV_FILE" "$ENV_FILE.bak.$(date +%Y%m%d_%H%M%S)"
    echo "(バックアップ保存: $ENV_FILE.bak.*)"
fi

# 入力ヘルパー
ask() {
    local prompt="$1"
    local default="$2"
    local var
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " var
        var="${var:-$default}"
    else
        read -p "$prompt: " var
    fi
    echo "$var"
}

ask_secret() {
    local prompt="$1"
    local var
    read -s -p "$prompt: " var
    echo ""
    echo "$var"
}

ask_optional() {
    local prompt="$1"
    local var
    read -p "$prompt (空Enterでスキップ): " var
    echo "$var"
}

echo "▼ あなたの基本情報"
EMAIL=$(ask "メインで使う Google アカウントのメールアドレス" "")
echo ""

echo "▼ Zoom API (docs/03_ZOOM_API_SETUP.md 参照)"
echo "  Zoom Marketplace で Server-to-Server OAuth アプリ作成後、以下を入力"
ZOOM_ACCOUNT_ID=$(ask_optional "ZOOM_ACCOUNT_ID")
ZOOM_CLIENT_ID=$(ask_optional "ZOOM_CLIENT_ID")
ZOOM_CLIENT_SECRET=$(ask_secret "ZOOM_CLIENT_SECRET (入力は非表示)")
echo ""

echo "▼ OpenRouter API (docs/04_OPENROUTER_SETUP.md 参照)"
OPENROUTER_API_KEY=$(ask_secret "OPENROUTER_API_KEY (入力は非表示)")
echo ""

echo "▼ Discord Bot (docs/05_DISCORD_BOT_SETUP.md 参照、後でもOK)"
DISCORD_BOT_TOKEN=$(ask_secret "DISCORD_BOT_TOKEN (入力は非表示、空Enterでスキップ)")
echo ""

echo "▼ Discord Webhook URLs (docs/06_DISCORD_WEBHOOK_SETUP.md 参照、後でもOK)"
WEBHOOK_NOTIFY=$(ask_optional "DISCORD_WEBHOOK_COURSE_NOTIFY")
WEBHOOK_ARCHIVE=$(ask_optional "DISCORD_WEBHOOK_COURSE_ARCHIVE")
echo ""

echo "▼ Google Calendar (docs/07_GOOGLE_OAUTH_SETUP.md 参照、後でもOK)"
GCAL=$(ask_optional "GCAL_TARGET_CALENDAR (カレンダーID)")
echo ""

echo "▼ Google Drive (Zoom録画のバックアップ先フォルダID、Driveで作成して取得)"
DRIVE_FOLDER=$(ask_optional "DRIVE_PARENT_FOLDER")
echo ""

echo "▼ Obsidian (任意、Vault使ってる人のみ)"
OBSIDIAN=$(ask_optional "OBSIDIAN_VAULT_PATH (絶対パス)")
echo ""

echo "▼ YouTube API (docs/08_YOUTUBE_API_SETUP.md 参照、後で youtube_oauth_setup.py で取得)"
YT_CLIENT_ID=$(ask_optional "YOUTUBE_CLIENT_ID")
YT_CLIENT_SECRET=$(ask_optional "YOUTUBE_CLIENT_SECRET")
echo ""

echo "▼ 講座情報(要約プロンプトに使われる)"
COURSE_NAME=$(ask "あなたの講座名(例: ○○講座)" "オンライン講座")
COURSE_HOST=$(ask_optional "主宰者名(任意)")
echo ""

# .env 生成
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh at $(date +"%Y-%m-%d %H:%M:%S")

# 必須
GOG_ACCOUNT=$EMAIL

# Zoom API
ZOOM_ACCOUNT_ID=$ZOOM_ACCOUNT_ID
ZOOM_CLIENT_ID=$ZOOM_CLIENT_ID
ZOOM_CLIENT_SECRET=$ZOOM_CLIENT_SECRET

# OpenRouter
OPENROUTER_API_KEY=$OPENROUTER_API_KEY

# Discord Bot
DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN

# Discord Webhooks
DISCORD_WEBHOOK_COURSE_NOTIFY=$WEBHOOK_NOTIFY
DISCORD_WEBHOOK_COURSE_ARCHIVE=$WEBHOOK_ARCHIVE

# Google Calendar / Drive
GCAL_TARGET_CALENDAR=$GCAL
DRIVE_PARENT_FOLDER=$DRIVE_FOLDER

# Obsidian (任意)
OBSIDIAN_VAULT_PATH=$OBSIDIAN
OBSIDIAN_ZOOM_SUBDIR=Transcripts/Zoom

# YouTube
YOUTUBE_CLIENT_ID=$YT_CLIENT_ID
YOUTUBE_CLIENT_SECRET=$YT_CLIENT_SECRET
YOUTUBE_REFRESH_TOKEN=

# 講座情報(要約プロンプト用)
COURSE_NAME=$COURSE_NAME
COURSE_HOST_NAME=$COURSE_HOST
EOF
chmod 600 "$ENV_FILE"

echo ""
echo "================================================="
echo "  ✅ $ENV_FILE を作成しました"
echo "================================================="
echo ""
echo "次のステップ:"
echo ""
echo "1. 空欄のキーは docs/ の該当ガイドを見て後で追加"
echo "2. テンプレJSON をコピー&編集:"
echo "    cp config/zoom_meeting_templates.example.json config/zoom_meeting_templates.json"
echo "    cp config/youtube_archive_discord_routes.example.json config/youtube_archive_discord_routes.json"
echo "3. YouTube 認証:"
echo "    python3 scripts/youtube_oauth_setup.py"
echo "4. 動作確認:"
echo "    python3 scripts/zoom_list_recordings.py 7"
echo "5. 詳しい使い方: README.md / docs/"
echo ""
